# Week4 Python Programming

In week4, we've covered:
* **Descriptive Statistics**:
    * mean
    * median
    * mode
    * variance
    * covariance

    
* **Matrix**:
    * python NumPy package

The best way to consolidate the knowledge in your mind is by practicing.<br>Please complete the part marked with <span style="color:green">**# TODO**</span>.

[Google](www.google.com) and [Python Documentation](https://docs.python.org/3/contents.html) are your good friends if you have any python questions.

Upload **Week4_PythonProgramming_Homework.ipynb** notebook to your Google Drive and open it with Google Colab.

## Basics of NumPy Array

[Numpy Documentation](https://numpy.org/)

### 1. Array Attributes

Import numpy and use `numpy.random.randint()` to create three random arrays:
* one-dimendional array
* two-dimensional array
* three-dimensional array

In [2]:
# TODO
#one_array = _____
#two_array = _____
#three_array = _____
# output array 
import numpy as ds 
one_array = ds.random.randint(low = 0, high = 5, size = 10) 
two_array = ds.random.randint(low = 5, size =(3, 6)) 
three_array = ds.random.randint(2, 10, (2, 3, 4))  
print ("Output 1D Array filled with random integers : ", one_array)  
print ("Output 2D Array filled with random integers : ", two_array)
print ("Output 3D Array filled with random integers : ", three_array) 


Output 1D Array filled with random integers :  [0 0 3 2 2 3 3 0 0 2]
Output 2D Array filled with random integers :  [[4 3 0 1 3 2]
 [0 3 2 3 4 2]
 [3 4 2 1 3 3]]
Output 3D Array filled with random integers :  [[[9 7 5 8]
  [4 6 8 6]
  [3 2 4 9]]

 [[8 6 2 5]
  [5 6 8 6]
  [2 5 7 8]]]


Check the `ndim`, `shape` and `size` of above three arrays.

In [4]:
# TODO
import numpy as np 
array = np.array([3, 1, 3, 2, 1, 4, 2, 4, 4, 1 ]) 
# Printing shape of array 
print("Shape of array: ", array.shape)  
# Printing size (total number of elements) of array 
print("Size of array: ", array.size) 
#Check the two dim, shape and size of above three arrays.

array = np.array( [[ 2, 4, 4], 
                 [ 2, 1, 4]] ) 

  
# Printing shape of array 
print("Shape of array: ", array.shape) 
  
# Printing size (total number of elements) of array 
print("Size of array: ", array.size) 


Shape of array:  (10,)
Size of array:  10


In [17]:
#Check the two dim, shape and size of above three arrays.
import numpy as np 
array = np.array( [[ 2, 4, 4], 
                 [ 2, 1, 4]] ) 

  
# Printing shape of array 
print("Shape of array: ", array.shape) 
  
# Printing size (total number of elements) of array 
print("Size of array: ", array.size) 

Shape of array:  (2, 3)
Size of array:  6


Create a length-5 **interger** array filled with zeros, a length-5 **float** arrays filled with ones.

In [0]:
# TODO
# create arrays
zeros_array = np.zeros(5).astype(int)
ones_array = np.ones(5)

# check arrays' data type
assert str(zeros_array.dtype) == 'int64'
assert str(ones_array.dtype) == 'float64' 

In [0]:
# TODO
zeros_array = _____
ones_array = _____

assert str(zeros_array.dtype) == 'int64'
assert str(ones_array.dtype) == 'float64' 

Create an interger array of 6 values evenly spaced between 10 and 20. 
Hint: use `linspace` and `astype`.

In [27]:
# TODO
import numpy as np   
# create array
values = np.linspace(10, 20, 6).astype(int)

# check array
print('value =', values)
print('value and data type: ', values.dtype)




value = [10 12 14 16 18 20]
value and data type:  int64


### 2. Indexing and Slicing

Print the last item in one_array.

In [13]:
# TODO
import numpy
# initializing list  
one_array = [1, 5, 6, 7, 4] 
  
# printing original list  
print ("The original list is : " +  str(one_array)) 
  
# using list indexing 
# to get first and last element of list 
res = [ one_array[0], one_array[-1] ]  
  
# printing result 
print ("The first and last element of list are : " +  str(res)) 


The original list is : [1, 5, 6, 7, 4]
The first and last element of list are : [1, 4]


Access all the values in the first row and second column of `three_array`.

In [32]:
# TODO
import numpy as np

three_array = np.random.randint(12,size=(8,8,8))
#three_array
print("first row and second column: ", three_array[0,1,:])



first row and second column:  [11 11  2  9  7 10  7  3]


Print elements after index 5 of `x`.

In [33]:
# TODO 
#Print elements after index 5 of x.
x = np.arange(20)
y = print(x)
x[5+1:]
print("Elements after index 5 ", x[5+1:])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Elements after index 5  [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Get every other element after index 5 of `x`.

In [35]:
# TODO
x = np.arange(20)
y = print(x)
x[5+1:]
print("Elements after index 5 ", x[5+2:len(x):2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Elements after index 5  [ 7  9 11 13 15 17 19]


Repalce all odd numbers in `x` with -1.

In [41]:
# TODO

x = np.arange(20)
y = print(x)
x[x%2!=0]=-1

print("Replaced odd numbers are ", x)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Replaced odd numbers are  [ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


### 3.Reshaping

Print the numbers from 1 to 9 as a row.

In [43]:
#3.Reshaping
#Print the numbers from 1 to 9 as a row.
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = a.reshape((2,2,3))
b


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Print the numbers from 1 to 9 as a column.


In [44]:
# TODO
# TODO
import numpy as np
z = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]])

#z.reshape(-1)
z.reshape(-1,1)
#array([[ 1],



array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

Print the numbers from 1 to 9 as a 3x3 grid.

### 4. Concatenating and Splitting

Concatenate array `x` and array `y` along axis= 0, and assign the result to variable `z`.

In [46]:
# TODO
x = np.linspace(2, 10, 3)
y = np.arange(3)
z = np.concatenate((x, y), axis=0)

print(z)

[ 2.  6. 10.  0.  1.  2.]


Stack `x`  and `y` vertically and assign result to variable `v`.

In [48]:
# TODO
#Stack x and y vertically and assign result to variable v.
# TODO
x = np.linspace(2, 10, 3)
y = np.arange(3)
v = np.stack((x, y), axis=0)
print(v)


[[ 2.  6. 10.]
 [ 0.  1.  2.]]


Split `v` to two arrays with equal number of elements.

In [49]:
#TODO
split_array_1, split_array_2 = np.split(v, 2)

print(split_array_1)
print(split_array_2)


[[ 2.  6. 10.]]
[[0. 1. 2.]]


## 5. Vectorize operation  
There are some cases in which you can replace loops with Numpy that use vector operations to make your computations a LOT faster.

Use a loop to find the intersection between `x` and `y`.

In [51]:
# TODO
import time
start = time.time()
x = np.arange(10000)
y = np.arange(800, 20000)

# your codes go here
x_y_intersection = []
# loop through x 
for ix in x:
    # check if ix is in y
    if ix in y:
        # add to the intersection list
        x_y_intersection.append(ix)

print("Intersection between x and y includes {} elements.".format(len(x_y_intersection)))
print('Duration: {} seconds'.format(time.time() - start))


Intersection between x and y includes 9200 elements.
Duration: 0.12498712539672852 seconds


Use Numpy's `intersect1d` method to get the intersection of the `x` and `y` arrays.

In [52]:
#TODO
start = time.time()

# your codes go here

x_y_intersection2 = np.intersect1d(x, y)
print("Intersection between x and y includes {} elements.".format(len(x_y_intersection2)))
print('Duration: {} seconds'.format(time.time() - start))

Intersection between x and y includes 9200 elements.
Duration: 0.007817506790161133 seconds


## Descriptive Satistics

The data is the results of a chemical analysis of wines grown in the same region in Italy by three different cultivators. There are thirteen different measurements taken for different constituents found in the three types of wine.

[Wine Data Set Description](https://archive.ics.uci.edu/ml/datasets/Wine)

In [53]:
# load dataset
from sklearn import datasets
wine_data = datasets.load_wine()['data']
wine_chemical = datasets.load_wine()['feature_names']
wine_class = datasets.load_wine()['target']



Datatype wine_data : <class 'numpy.ndarray'>
Datatype wine_chemical : <class 'list'>
Datatype wine_class: <class 'numpy.ndarray'>


1. What are the types of  variable `wine_data`, `wine_chemical` and `wine_class`?

In [54]:
# TODO
print ('Datatype wine_data :', type(wine_data))
print ('Datatype wine_chemical :', type(wine_chemical))
print ('Datatype wine_class:',  type(wine_class))


Datatype wine_data : <class 'numpy.ndarray'>
Datatype wine_chemical : <class 'list'>
Datatype wine_class: <class 'numpy.ndarray'>


2. What are the data types in variable `wine_data`, `wine_chemical` and `wine_class`

In [57]:
# TODO
print("wine_data data type:", wine_data.dtype)
print("wine_chemical data type:", set([type(x) for x in wine_chemical]))
print("wine_class data type:",wine_class.dtype)

wine_data data type: float64
wine_chemical data type: {<class 'str'>}
wine_class data type: int64


3. What are the shape/length of `wine_data`, `wine_chemical` and `wine_class`?

In [61]:
# TODO

print("wine_data shape:", wine_data.shape)
print("wine_chemical shape:", len(wine_chemical))
print("wine_class shape:", wine_class.shape)



wine_data shape: (178, 13)
wine_chemical shape: 13
wine_class shape: (178,)


4. How many unique wine classes can you find in `wine_class`?

In [62]:
# TODO
def unique(list1): 
    x = np.array(list1) 
    print(np.unique(x))        
# driver code 
list1 = wine_class
print("the unique values from 1st list is") 
unique(list1) 
  

the unique values from 1st list is
[0 1 2]


5. How many samples in `wine_data` does each class of wine have? Which wine has the most samples, and which wine has the least samples?

In [66]:
# TODO
# count samples for each wine class 
wine_counts={'wine class '+str(wine): sum(wine_class==wine) for wine in set(wine_class)}

# extract wine class names and sample counts
wine_class_counts = list(wine_counts.values())
wine_class_names = list(wine_counts.keys())

# identify wine class with the most and least samples
wine_class_name_max = wine_class_names[wine_class_counts.index(max(wine_class_counts))]
wine_class_name_min = wine_class_names[wine_class_counts.index(min(wine_class_counts))]

print(wine_counts)
print("{} has the most samples.".format(wine_class_name_max))
print("{} has the least samples.".format(wine_class_name_min))

{'wine class 0': 59, 'wine class 1': 71, 'wine class 2': 48}
wine class 1 has the most samples.
wine class 2 has the least samples.


6. What is the mean, median `alcohol` level and the standard deviation for each type of wine? How many wine class 0 samples have alcohol level that is two standard deviation below the mean of all samples?

In [68]:
# TODO
print(np.mean(wine_data),np.mean(wine_data[:,0]))
np.mean(wine_data[:,0])
print(np.median(wine_data),np.median(wine_data[:,0]))
print(np.std(wine_data),np.std(wine_data[:,0]))

69.13366292091617 13.00061797752809
2.685 13.05
215.74620420485243 0.8095429145285168


7. Can you find the chemical that has the highest correlation with `alcohol` for wine class 1?  
Hint: if you use [numpy.corrcoef](https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html) for calculation, pay attention to the shape of the parameters passed in.

In [69]:
# TODO
print(np.corrcoef(wine_data),np.corrcoef(wine_data[:,0]))


[[1.         0.99971544 0.9994164  ... 0.99965667 0.99968167 0.99840099]
 [0.99971544 1.         0.99992977 ... 0.99878998 0.99882897 0.99688785]
 [0.9994164  0.99992977 1.         ... 0.9982921  0.99833736 0.99621008]
 ...
 [0.99965667 0.99878998 0.9982921  ... 1.         0.9999972  0.99950589]
 [0.99968167 0.99882897 0.99833736 ... 0.9999972  1.         0.99948599]
 [0.99840099 0.99688785 0.99621008 ... 0.99950589 0.99948599 1.        ]] 1.0


## Submission

Download completed **Week4_PythonProgramming_Homework.ipynb** from Google Colab and commit to your personal Github repo you shared with the faculty.